#!/bin/bash

# $SWITCH_STATE is a value provided through the udev environment

SWITCH_STATE="$(cat /sys/class/switch/h2w/state)"
PULSE_SERVER="unix:/run/user/32011/pulse/native"
export PULSE_COOKIE=/home/phablet/.config/pulse/cookie


#headset without mic
if [ "$SWITCH_STATE" == "2" ]; then
    /usr/bin/pactl --server $PULSE_SERVER set-card-profile droid_card.primary voicecall 
    /usr/bin/pactl --server $PULSE_SERVER set-sink-port sink.primary_output output-wired_headset
    /usr/bin/pactl --server $PULSE_SERVER set-sink-volume sink.primary_output 200
#headset with mic
elif [ "$SWITCH_STATE" == "1" ]; then
    /usr/bin/pactl --server $PULSE_SERVER set-card-profile droid_card.primary voicecall 
    /usr/bin/pactl --server $PULSE_SERVER set-sink-port sink.primary_output output-wired_headset
    /usr/bin/pactl --server $PULSE_SERVER set-sink-volume sink.primary_output 200
    /usr/bin/pactl --server $PULSE_SERVER set-source-port source.record_24_primary_input input-wired_headset
#no headset
elif [ "$SWITCH_STATE" == "0" ]; then
    /usr/bin/pactl --server $PULSE_SERVER set-card-profile droid_card.primary voicecall 
    /usr/bin/pactl --server $PULSE_SERVER set-sink-port sink.primary_output output-parking 
    /usr/bin/pactl --server $PULSE_SERVER set-sink-port sink.primary_output output-speaker
    /usr/bin/pactl --server $PULSE_SERVER set-sink-volume sink.primary_output 200
    /usr/bin/pactl --server $PULSE_SERVER set-source-port source.record_24_primary_input input-builtin_mic
fi

